package com.wip.manhwaTranslatorAI

import com.wip.common.models.AdvancedOCRResult
import com.wip.common.models.OCRResult
import org.wip.plugintoolkit.api.HostFileSystem
import org.wip.plugintoolkit.api.OS
import org.wip.plugintoolkit.api.PluginContext
import org.wip.plugintoolkit.api.PluginLogger
import org.wip.plugintoolkit.api.annotations.Capability
import org.wip.plugintoolkit.api.annotations.CapabilityInput
import org.wip.plugintoolkit.api.annotations.CapabilityOutput
import org.wip.plugintoolkit.api.annotations.CapabilityParam
import org.wip.plugintoolkit.api.annotations.PluginInfo
import org.wip.plugintoolkit.api.annotations.PluginLoad
import org.wip.plugintoolkit.api.annotations.PluginSetting
import org.wip.plugintoolkit.api.annotations.PluginSetup
import org.wip.plugintoolkit.api.annotations.PluginUpdate
import org.wip.plugintoolkit.api.annotations.PluginValidate
import org.wip.plugintoolkit.api.annotations.RequiresSetting

data class TranslatorAISettings(
    @PluginSetting(
        description = "API Key for Google services",
        required = true,
        secret = true
    )
    val googleApiKey: String = "",

    @PluginSetting(
        description = "Use structured output (JSON schema). Disable if the model does not support it.",
        defaultValue = "true",
        required = true 
    )
    val useStructuredOutput: Boolean = true,

    @PluginSetting(
        description = "URL for LM Studio (e.g. http://localhost:1234/v1)",
        required = false
    )
    val lmStudioUrl: String? = "http://localhost:1234/v1",

    @PluginSetting(
        description = "API Key for LM Studio",
        required = false,
        secret = true
    )
    val lmStudioApiKey: String? = "lm-studio",

    @PluginSetting(
        description = "The specific model name to request from LM Studio",
        required = false
    )
    val lmStudioModelName: String? = "default-model"
)

enum class AIModel(val id: String) {
    GEMMA_26B("gemma-4-26b-a4b-it"),
    GEMMA_31B("gemma-4-31b-it"),
    GEMINI_3_5_FLASH("gemini-3.5-flash"),
    GEMINI_3_1_FLASH_LITE("gemini-3.1-flash-lite"),
    @RequiresSetting(["lmStudioModelName", "lmStudioApiKey", "lmStudioUrl"])
    LM_STUDIO("lm-studio")
}

@PluginInfo(
    id = "com.wip.manhwa_translator_ai",
    name = "Manhwa Translator AI",
    version = "1.4.0",
    description = "Translate text from Manhwa/Manga into Italian using Google AI via Koog",
    supportedOs = [OS.WINDOWS]
)
class TranslatorAI(val settings: TranslatorAISettings) {

    @PluginLoad
    fun onLoad(logger: PluginLogger): Result<Unit> {
        logger.info("[TranslatorAI] onLoad: Initializing Manhwa Translator AI (has googleApiKey: ${settings.googleApiKey.isNotBlank()}, useStructuredOutput: ${settings.useStructuredOutput}, lmStudioUrl: ${settings.lmStudioUrl})")
        return Result.success(Unit)
    }

    @Capability(
        name = "translate_ocr",
        description = "Translates an OCRResult into Italian using Google AI"
    )
    suspend fun translateOcr(
        @CapabilityParam(
            description = "The OCR Result to translate"
        )
        inputOcr: OCRResult,
        @CapabilityParam(
            description = "Dictionary of words/actions to keep the translation coherent",
            defaultValue = ""
        )
        dictionary: String? = "",
        @CapabilityParam(
            description = "The Gemini Model ID to use",
            defaultValue = "GEMMA_31B"
        )
        model: AIModel,
        @CapabilityInput(
            description = "Path to the folder containing the images",
            semanticTypes = ["path/folder"]
        )
        inputFolder: String,
        @CapabilityOutput(
            description = "Directory to save translation result",
            autogeneratedPattern = "{model}/translation",
            semanticTypes = ["path/folder"]
        )
        outputDir: String,
        @CapabilityOutput(
            description = "Temporary directory for summary images",
            autogeneratedPattern = "{model}/temp_summary",
            semanticTypes = ["path/folder"]
        )
        tempSummaryDir: String,
        @CapabilityParam(
            description = "Send images to AI for visual context (Requires Gemini 1.5/Gemma)",
            defaultValue = "false"
        )
        useContextImages: Boolean? = false,
        @CapabilityParam(
            description = "Generate a global summary context from all chapter images using Gemini 3.1 Flash Lite",
            defaultValue = "true"
        )
        generateChapterSummary: Boolean? = true,
        @CapabilityParam(
            description = "Save the translation result in a json",
            defaultValue = "true"
        )
        save: Boolean? = true,
        context: PluginContext,
        hostFs: HostFileSystem
    ): OCRResult {
        val logger = context.logger
        val effectiveDict = dictionary ?: ""
        val effectiveContextImages = useContextImages ?: false
        val effectiveSummary = generateChapterSummary ?: true
        logger.info("Manhwa Translator AI (Basic OCRResult) started. Model: ${model.id}")
        logger.info("Input size: ${inputOcr.texts.size} | Dictionary size: ${effectiveDict.length} | Context Images: $effectiveContextImages | Global Summary: $effectiveSummary")

        return try {
            val service = KoogAITranslatorService(context, settings, hostFs)
            val translatedTexts = service.performTranslation(
                input = inputOcr.texts,
                dictionary = effectiveDict,
                apiKey = settings.googleApiKey,
                useStructuredOutput = settings.useStructuredOutput,
                modelId = model.id,
                pageNames = inputOcr.pageNames,
                inputFolder = inputFolder,
                outputDir = outputDir,
                tempSummaryDir = tempSummaryDir,
                useContextImages = effectiveContextImages,
                generateChapterSummary = effectiveSummary,
                save = save ?: true
            )
            logger.info("Basic OCR Translation completed.")
            inputOcr.copy(texts = translatedTexts)
        } catch (e: Throwable) {
            val msg = "Basic OCR Translation failed: ${e::class.simpleName}: ${e.message}"
            logger.error(msg)
            if (e is Error) {
                logger.error("A critical Error occurred: ${e.stackTraceToString()}")
            }
            throw RuntimeException(msg, e)
        }
    }

    @Capability(
        name = "translate",
        description = "Translates a list of strings into Italian using Google AI")
    suspend fun translate(
            @CapabilityParam(
                description = "List of text strings to translate"
            )
            input: List<String>,
            @CapabilityParam(
                description = "Dictionary of words/actions to keep the translation coherent",
                defaultValue = ""
            )
            dictionary: String? = "",
            @CapabilityParam(
                description = "The Gemini Model ID to use",
                defaultValue = "GEMMA_31B"
            )
            model: AIModel,
            @CapabilityParam(
                description = "List of page names matching the input texts (from OCR)",
                defaultValue = "[]"
            )
            pageNames: List<String>? = emptyList(),
            @CapabilityInput(
                description = "Path to the folder containing the images",
                semanticTypes = ["path/folder"]
            )
        inputFolder: String,
            @CapabilityOutput(
                description = "Directory to save translation result",
                autogeneratedPattern = "{model}/translation",
                semanticTypes = ["path/folder"]
            )
        outputDir: String,
            @CapabilityOutput(
                description = "Temporary directory for summary images",
                autogeneratedPattern = "{model}/temp_summary",
                semanticTypes = ["path/folder"]
            )
        tempSummaryDir: String,
            @CapabilityParam(
                description = "Send images to AI for visual context (Requires Gemini 1.5/Gemma)",
                defaultValue = "false"
            )
            useContextImages: Boolean? = false,
            @CapabilityParam(
                description = "Generate a global summary context from all chapter images using Gemini 3.1 Flash Lite",
                defaultValue = "true"
            )
            generateChapterSummary: Boolean? = true,
            @CapabilityParam(
                description = "Save the translation result in a json",
                defaultValue = "true"
            )
            save: Boolean? = true,
            context: PluginContext,
            hostFs: HostFileSystem
    ): List<String> {
        val logger = context.logger
        val effectiveDict = dictionary ?: ""
        val effectiveContextImages = useContextImages ?: false
        val effectiveSummary = generateChapterSummary ?: true
        logger.info("Manhwa Translator AI started. Model: ${model.id}")
        logger.info("Input size: ${input.size} | Dictionary size: ${effectiveDict.length} | Context Images: $effectiveContextImages | Global Summary: $effectiveSummary")

        return try {
            val service = KoogAITranslatorService(context, settings, hostFs)
            val result = service.performTranslation(input, effectiveDict, settings.googleApiKey, settings.useStructuredOutput, model.id, pageNames, inputFolder, outputDir, tempSummaryDir, effectiveContextImages, effectiveSummary, save ?: true)
            logger.info("Translation completed.")
            result
        } catch (e: Throwable) {
            val msg = "Translation failed: ${e::class.simpleName}: ${e.message}"
            logger.error(msg)
            if (e is Error) {
                logger.error("A critical Error occurred: ${e.stackTraceToString()}")
            }
            throw RuntimeException(msg, e)
        }
    }

    @Capability(
        name = "translate_advanced_ocr",
        description = "Translates an AdvancedOCRResult into Italian using Google AI"
    )
    suspend fun translateAdvancedOcr(
            @CapabilityParam(
                description = "The Advanced OCR Result to translate"
            )
            inputOcr: AdvancedOCRResult,
            @CapabilityParam(
                description = "Dictionary of words/actions to keep the translation coherent",
                defaultValue = ""
            )
            dictionary: String? = "",
            @CapabilityParam(
                description = "The AI Model to use",
                defaultValue = "GEMMA_31B"
            )
            model: AIModel,
            @CapabilityInput(
                description = "Path to the folder containing the images",
                semanticTypes = ["path/folder"]
            )
        inputFolder: String,
            @CapabilityOutput(
                description = "Directory to save translation result",
                autogeneratedPattern = "{model}/translation",
                semanticTypes = ["path/folder"]
            )
        outputDir: String,
            @CapabilityOutput(
                description = "Temporary directory for summary images",
                autogeneratedPattern = "{model}/temp_summary",
                semanticTypes = ["path/folder"]
            )
        tempSummaryDir: String,
            @CapabilityParam(
                description = "Send images to AI for visual context (Requires Gemini 1.5/Gemma)",
                defaultValue = "false"
            )
            useContextImages: Boolean? = false,
            @CapabilityParam(
                description = "Generate a global summary context from all chapter images using Gemini 3.1 Flash Lite",
                defaultValue = "true"
            )
            generateChapterSummary: Boolean? = true,
            @CapabilityParam(
                description = "Save the translation result in a json",
                defaultValue = "true"
            )
            save: Boolean? = true,
            context: PluginContext,
            hostFs: HostFileSystem
    ): AdvancedOCRResult {
        val logger = context.logger
        val effectiveDict = dictionary ?: ""
        val effectiveContextImages = useContextImages ?: false
        val effectiveSummary = generateChapterSummary ?: true
        logger.info("Manhwa Translator AI (Advanced OCR) started. Model: ${model.id}")
        logger.info("Input size: ${inputOcr.texts.size} | Dictionary size: ${effectiveDict.length} | Context Images: $effectiveContextImages | Global Summary: $effectiveSummary")

        return try {
            val service = KoogAITranslatorService(context, settings, hostFs)
            val translatedTexts = service.performTranslation(
                input = inputOcr.texts,
                dictionary = effectiveDict,
                apiKey = settings.googleApiKey,
                useStructuredOutput = settings.useStructuredOutput,
                modelId = model.id,
                pageNames = inputOcr.pageNames,
                inputFolder = inputFolder,
                outputDir = outputDir,
                tempSummaryDir = tempSummaryDir,
                useContextImages = effectiveContextImages,
                generateChapterSummary = effectiveSummary,
                save = save ?: true
            )
            logger.info("Advanced OCR Translation completed.")
            inputOcr.copy(texts = translatedTexts)
        } catch (e: Throwable) {
            val msg = "Advanced OCR Translation failed: ${e::class.simpleName}: ${e.message}"
            logger.error(msg)
            if (e is Error) {
                logger.error("A critical Error occurred: ${e.stackTraceToString()}")
            }
            throw RuntimeException(msg, e)
        }
    }

    @PluginSetup
    suspend fun setup(context: PluginContext): Result<Unit> {
        val logger = context.logger
        logger.info("[TranslatorAI] setup: Starting Manhwa Translator AI setup...")
        logger.info("[TranslatorAI] setup: Setup completed successfully.")
        return Result.success(Unit)
    }

    @PluginUpdate
    suspend fun update(context: PluginContext): Result<Unit> {
        context.logger.info("[TranslatorAI] update: Manhwa Translator AI update complete.")
        return Result.success(Unit)
    }

    @PluginValidate
    suspend fun validate(context: PluginContext): Result<Unit> {
        val logger = context.logger
        logger.info("[TranslatorAI] validate: Validating Manhwa Translator AI requirements...")
        logger.info("[TranslatorAI] validate: Google API Key configured: ${settings.googleApiKey.isNotBlank()}")
        logger.info("[TranslatorAI] validate: Validation passed successfully.")
        return Result.success(Unit)
    }
}
