package com.wip.ocrAI

import com.wip.common.models.AdvancedOCRResult
import com.wip.common.models.ModelCatalog
import com.wip.common.models.ModelManager
import com.wip.common.models.OCRResult
import com.wip.ocrAI.models.AIModel
import com.wip.ocrAI.models.OcrDownloadModel
import com.wip.ocrAI.models.OcrIASettings
import org.wip.plugintoolkit.api.HostFileSystem
import org.wip.plugintoolkit.api.OS
import org.wip.plugintoolkit.api.PluginContext
import org.wip.plugintoolkit.api.PluginLogger
import org.wip.plugintoolkit.api.annotations.Capability
import org.wip.plugintoolkit.api.annotations.CapabilityInput
import org.wip.plugintoolkit.api.annotations.CapabilityOutput
import org.wip.plugintoolkit.api.annotations.CapabilityParam
import org.wip.plugintoolkit.api.annotations.PluginAction
import org.wip.plugintoolkit.api.annotations.PluginInfo
import org.wip.plugintoolkit.api.annotations.PluginLoad
import org.wip.plugintoolkit.api.annotations.PluginLocks
import org.wip.plugintoolkit.api.annotations.PluginSetup
import org.wip.plugintoolkit.api.annotations.PluginUpdate
import org.wip.plugintoolkit.api.annotations.PluginValidate

@PluginInfo(
    id = "com.wip.ocr_ia",
    name = "OCR IA",
    version = "2.6.0",
    description = "Advanced OCR plugin using Google AI, Anthropic, OpenAI, and LMStudio via Koog",
    supportedOs = [OS.WINDOWS]
)
class OCR_IA(val settings: OcrIASettings = OcrIASettings()) {

    @PluginLoad
    fun onLoad(logger: PluginLogger): Result<Unit> {
        logger.info("[OCR_IA] onLoad: Initializing OCR IA (has googleApiKey: ${settings.googleApiKey.isNotBlank()}, anthropicApiKey: ${!settings.anthropicApiKey.isNullOrBlank()}, openAIApiKey: ${!settings.openAIApiKey.isNullOrBlank()})")
        return Result.success(Unit)
    }

    @PluginLocks
    suspend fun checkLocks(context: PluginContext): Map<String, Boolean> {
        val logger = context.logger
        logger.info("[OCR_IA] checkLocks: Checking OCR model locks...")
        val locks = mutableMapOf<String, Boolean>()
        for (m in OcrDownloadModel.entries) {
            val installed = ModelManager.Default.isModelInstalled(m.modelId, context.fileSystem, logger)
            logger.info("[OCR_IA] checkLocks: Model ${m.name} (${m.modelId}) installed: $installed")
            locks[ModelCatalog.getLockKey(m.modelId)] = installed
            locks[m.modelId] = installed
        }
        logger.info("[OCR_IA] checkLocks: Completed OCR locks check: $locks")
        return locks
    }

    @PluginAction(
        name = "Download Model",
        description = "Downloads a specific ONNX OCR model and descriptor to local plugin storage"
    )
    suspend fun downloadModel(
        @CapabilityParam(description = "Select OCR model to download", defaultValue = "\"UNLIMITED_OCR\"")
        model: OcrDownloadModel? = OcrDownloadModel.UNLIMITED_OCR,
        context: PluginContext
    ) {
        val logger = context.logger
        val targetModel = model ?: OcrDownloadModel.UNLIMITED_OCR
        logger.info("[OCR_IA] downloadModel action triggered for: ${targetModel.name} (${targetModel.modelId})")
        val result = ModelManager.Default.downloadModel(targetModel.modelId, context)
        if (result.isFailure) {
            logger.error("[OCR_IA] downloadModel action failed for ${targetModel.modelId}: ${result.exceptionOrNull()?.message}")
            throw result.exceptionOrNull() ?: RuntimeException("Failed to download model ${targetModel.modelId}")
        }
        logger.info("[OCR_IA] downloadModel action succeeded for: ${targetModel.modelId}")
    }

    @PluginAction(
        name = "Download All Models",
        description = "Downloads all required ONNX OCR models and descriptors to local plugin storage"
    )
    suspend fun downloadAllModels(context: PluginContext) {
        val ocrIds = OcrDownloadModel.entries.map { it.modelId }
        val result = ModelManager.Default.downloadModels(ocrIds, context)
        if (result.isFailure) {
            throw result.exceptionOrNull() ?: RuntimeException("Failed to download all models")
        }
    }
    
    @Capability(
        name = "ocr",
        description = "Performs basic OCR on an image or a folder of images"
    )
    suspend fun ocr(
        @CapabilityInput(
            description = "Path to image or folder",
            semanticTypes = ["path/folder"]
        )
        input: String,
        @CapabilityParam(description = "Save output to a .txt file alongside each image", defaultValue = "true")
        save: Boolean,
        @CapabilityOutput(
            description = "Custom output directory",
            autogeneratedPattern = "{input}/ocr_result/",
            semanticTypes = ["path/folder"]
        )
        outputDir: String,
        @CapabilityParam(description = "Whether to use native structured output (might not be supported by all models)", defaultValue = "false")
        useStructuredOutput: Boolean,
        @CapabilityParam(description = "Whether to save the thinking inside the json", defaultValue = "false")
        saveThinking: Boolean,
        @CapabilityParam(description = "The AI Model to use", defaultValue = "GEMMA_26B")
        model: AIModel,
        context: PluginContext,
        hostFs: HostFileSystem
    ): OCRResult {
        val logger = context.logger
        logger.info("OCR IA (Basic) v2.4.0 started. Model: ${model.id}")
        logger.info("Input: $input | Save: $save | OutputDir: '$outputDir' | StructuredOutput: $useStructuredOutput")

        return try {
            if (model == AIModel.UNLIMITED_OCR) {
                val runner = UnlimitedOcrRunner(context, hostFs)
                return runner.performOcr(input, save, outputDir, useStructuredOutput, saveThinking)
            }
            val service = KoogOcrService(context, settings, hostFs)
            val ocrResult = service.performOcr(input, save, outputDir, useStructuredOutput, saveThinking, model)
            OCRResult(ocrResult.texts, ocrResult.bb, ocrResult.pageNumbers, ocrResult.pageNames, ocrResult.failedFiles)
        } catch (e: Throwable) {
            val msg = "OCR failed: ${e::class.simpleName}: ${e.message}"
            logger.error(msg)
            if (e is Error) {
                logger.error("A critical Error occurred: ${e.stackTraceToString()}")
            }
            throw RuntimeException(msg, e)
        }
    }

    @Capability(
        name = "advanced_ocr",
        description = "Performs advanced OCR extracting exact balloon and text boxes, shapes, text orientation, sparsity, and color."
    )
    suspend fun advancedOcr(
        @CapabilityInput(
            description = "Path to image or folder",
            semanticTypes = ["path/folder"]
        )
        input: String,
        @CapabilityParam(description = "Save output to a .json file alongside each image", defaultValue = "true")
        save: Boolean,
        @CapabilityOutput(
            description = "Custom output directory",
            autogeneratedPattern = "{input}/ocr_result/",
            semanticTypes = ["path/folder"]
        )
        outputDir: String,
        @CapabilityParam(description = "Whether to use native structured output (might not be supported by all models)", defaultValue = "false")
        useStructuredOutput: Boolean,
        @CapabilityParam(description = "Whether to save the thinking inside the json", defaultValue = "false")
        saveThinking: Boolean,
        @CapabilityParam(description = "The AI Model to use", defaultValue = "GEMMA_31B")
        model: AIModel,
        context: PluginContext,
        hostFs: HostFileSystem
    ): AdvancedOCRResult {
        val logger = context.logger
        logger.info("OCR IA (Advanced) v2.4.0 started. Model: ${model.id}")
        logger.info("Input: $input | Save: $save | OutputDir: '$outputDir' | StructuredOutput: $useStructuredOutput")

        return try {
            if (model == AIModel.UNLIMITED_OCR) {
                val runner = UnlimitedOcrRunner(context, hostFs)
                return runner.performAdvancedOcr(input, save, outputDir, useStructuredOutput, saveThinking)
            }
            val service = KoogOcrService(context, settings, hostFs)
            val ocrResult = service.performAdvancedOcr(input, save, outputDir, useStructuredOutput, saveThinking, model)
            AdvancedOCRResult(
                texts = ocrResult.texts,
                balloonBoxes = ocrResult.balloonBoxes,
                textBoxes = ocrResult.textBoxes,
                shapes = ocrResult.shapes,
                fontStyles = ocrResult.fontStyles,
                fontFamilies = ocrResult.fontFamilies,
                textAngles = ocrResult.textAngles,
                isSparse = ocrResult.isSparse,
                textColors = ocrResult.textColors,
                hasBorder = ocrResult.hasBorder,
                borderColors = ocrResult.borderColors,
                pageNumbers = ocrResult.pageNumbers,
                pageNames = ocrResult.pageNames,
                failedFiles = ocrResult.failedFiles
            )
        } catch (e: Throwable) {
            val msg = "Advanced OCR failed: ${e::class.simpleName}: ${e.message}"
            logger.error(msg)
            if (e is Error) {
                logger.error("A critical Error occurred: ${e.stackTraceToString()}")
            }
            throw RuntimeException(msg, e)
        }
    }

    @PluginSetup
    suspend fun setup(context: PluginContext): Result<Unit> {
        val logger = context.logger
        logger.info("[OCR_IA] setup: Starting OCR IA plugin setup...")
        logger.info("[OCR_IA] setup: Setup finished successfully.")
        return Result.success(Unit)
    }

    @PluginUpdate
    suspend fun update(context: PluginContext): Result<Unit> {
        context.logger.info("[OCR_IA] update: OCR IA update hook complete.")
        return Result.success(Unit)
    }

    @PluginValidate
    suspend fun validate(context: PluginContext): Result<Unit> {
        val logger = context.logger
        logger.info("[OCR_IA] validate: Validating OCR IA plugin requirements...")
        logger.info("[OCR_IA] validate: Google API Key configured: ${settings.googleApiKey.isNotBlank()}")
        logger.info("[OCR_IA] validate: Validation passed successfully.")
        return Result.success(Unit)
    }
}
